package com.serverless;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

@DynamoDBTable(tableName = "Bookshop-Appointments")
@DynamoDBDocument
public class appointmentmodel {
    private String id;
    private String contact;
    private String date;
    private String name;
    private String time;

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey


    public String getId() {
        return id;
    }

    @DynamoDBAttribute(attributeName = "contact")
    public String getContact() {
        return contact;
    }

    @DynamoDBAttribute(attributeName = "date")
    public String getDate() {
        return date;
    }

    @DynamoDBAttribute(attributeName = "name")
    public String getName() {
        return name;
    }

    @DynamoDBAttribute(attributeName = "time")
    public String getTime() {
        return time;
    }


    public void setId(String id) {
        this.id = id;
    }


    public void setContact(String contact) {
        this.contact = contact;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setTime(String time) {
        this.time = time;
    }

}
